Repository codingindia/travel-safe, pull requests merged in 2020-04, with the labels that each got.

#39 Added CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
  README.md
Labels: beginner, gssoc20

#38 Action stale
  .github/workflows/stale.yml
Labels: beginner

#41 Created splash screen. (Solved)
  components/lib/main.dart
  components/pubspec.lock
  components/pubspec.yaml
Labels: easy, gssoc20

#60 fixed error
  components/lib/screens/register.dart
Labels: easy, gssoc20
